version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "hearthstone*"
        dependency-type: "direct"
    insecure-external-code-execution: allow
    registries: "*"