version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "hearthstone"
        dependency-type: "all"
      - dependency-name: "hearthstone-data"
        dependency-type: "all"
    insecure-external-code-execution: allow
    registries: "*"